# webserver
server:
  port: 8080
  context-path: /
  session:
    timeout: 1800

# logging
logging:
  level:
    org.springframework: info
    org.springframework.web.servlet.mvc: info
    com.fastweb: debug

#mysql config
spring:
  http:
    multipart:
      max-request-size: 210Mb
      max-file-size: 210Mb
  jmx:
    enabled: false

################################################################################ 
# 数据库配置
################################################################################    
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true
    username: root
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    maximum-pool-size: 50
    connection-timeout: 5000
    max-wait: 10000
    max-idle: 10
    min-idle: 5
    test-while-idle: true
    validation-query: SELECT 1